version: '2.1'
services:
  mongodb:
    image: mongo:3.4.2
    volumes:
      - mongo-data:/data/db
      - ./priv/mongo-backup:/data/backup
    logging:
      driver: syslog
    ports:
      - "27017:27017"
  arduino-builder:
    build: https://github.com/rosetta-home/docker-arduino-builder.git
    volumes:
      - arduino-data:/data/arduino
      - ./priv/firmware:/data/firmware
      - ./priv/systems/RFM69-USB-Gateway/libraries:/data/gateway
      - ./priv/systems/hardware_verification/libraries:/data/hardware_verification
      - ./priv/systems/Touchstone/libraries:/data/touchstone
      - ./priv/systems/RFM69-USB-Gateway/firmware:/code/gateway
      - ./priv/systems/Touchstone/firmware:/code/touchstone
      - ./priv/systems/hardware_verification/firmware:/code/hardware_verification
      - ./priv/build/touchstone:/build/touchstone
  nerves-firmware:
    build: https://github.com/rosetta-home/docker-nerves-firmware.git
    volumes:
      - nerves-data:/data/nerves
      - ./priv/systems/rosetta_home:/app
      - ./priv/firmware/hub:/app/apps/fw/_images
      - ./priv/build/hub:/app/apps/fw/_build
      - ./priv/build/hub:/root/.nerves
    working_dir: /app/apps/fw
    env_file:
      - nerves-firmware.prod.env
  avrdude:
    image: akshmakov/avrdude
  easypki:
    build: /app/docker-easypki
    volumes:
      - ./priv/certs:/data/easypki
    env_file:
      - easypki.prod.env


volumes:
  mongo-data:
    driver: local
  arduino-data:
    driver: local
  nerves-data:
    driver: local
