version: '2.1'
services:
  mongodb:
    image: mongo:3.4.2
    volumes:
      - mongo-data:/data/db
      - ./priv/mongo-backup:/data/backup
    logging:
      driver: syslog
    ports:
      - "27017:27017"

volumes:
  mongo-data:
    driver: local
